drive:
    ros__parameters:
        visualization: false
        # model_path: "/lanefollowing/ros2_ws/src/lane_following/model/model.h5"
        # model_path: "/lanefollowing/ros2_ws/src/lane_following/train/model/2021-06-15T02:09:38.h5"
        # model_path: "/lanefollowing/ros2_ws/src/lane_following/train/model/v1.h5"
        model_path: /lanefollowing/ros2_ws/src/lane_following/train/model/first-working.h5
        camera_topic: "/simulator/sensor/camera/center/compressed"
        control_topic: "/lanefollowing/steering_cmd"